title: "Nav2 API Docs"
description: "Developer-friendly Nav2 API documentation"
baseurl: ""
url: "https://api.nav2.org"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Distribution data for the homepage
collections:
  distributions:
    output: false
  nav2_distributions:
    output: false
  action_docs:
    output: true
    permalink: /:collection/:name/
  srv_docs:
    output: true
    permalink: /:collection/:name/

exclude:
  - .github/
  - scripts/
  - doxygen/
  - Gemfile*
  - README.md
  - LICENSE