title: "ROS 2 rclcpp Documentation"
description: "Developer-friendly ROS 2 rclcpp API documentation"
baseurl: "/rosdox.nav2.org"
url: "https://[username].github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Distribution data for the homepage
collections:
  distributions:
    output: false

exclude:
  - .github/
  - scripts/
  - doxygen/
  - Gemfile*
  - README.md
  - LICENSE