title: "ROS 2 API Docs"
description: "Developer-friendly ROS 2 rclcpp and RCL API documentation"
baseurl: ""
url: "https://rosdox.nav2.org"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Distribution data for the homepage
collections:
  distributions:
    output: false
  nav2_distributions:
    output: false

exclude:
  - .github/
  - scripts/
  - doxygen/
  - Gemfile*
  - README.md
  - LICENSE